### ISSUE TITLE
Plugin does nothing

### ISSUE THREAD

**Issue by YamiteruXYZ** [JonasKruckenberg/vite-imagetools#2]
I've installed this plugin and added it in my vite config. I import image as `./01.jpeg?format=webp` and when I do `vite build` it doesn't generate webp version of that image. Any ideas why it doesn't work?

**Comment by JonasKruckenberg** [comment]
Hey thanks for your feedback!
How do you import your image? (In the template,or script part?)
I'm aware of a couple of problems that I'm actively trying to solve at the moment (will be published as version 3 soon hopefully).

Currently importing images involves a lot of fighting vite, sadly. 
For example importing images in css does not work at all because the import never gets relayed to plugins.

You can however try to import your image in the script section of your component and use it as a variable.

**Comment by YamiteruXYZ** [comment]
This is how I import it:

```typescript
// @ts-ignore
import image from "./images/01.jpeg?format=webp";
import Work from "../../../src/type/Work";


const work01: Work = {
  slug: "work-01",
  title: "Work 01",
  image,
};


export default work01;

```

**Comment by YamiteruXYZ** [comment]
This is how the output of `vite build` looks like:

![image](https://user-images.githubusercontent.com/34185465/110129810-a6c82d80-7dc8-11eb-9a5b-cc26d9ffb013.png)
 
And this is how the image looks in network tab:

![image](https://user-images.githubusercontent.com/34185465/110129885-bcd5ee00-7dc8-11eb-9ee5-8338bbb95553.png)

**Comment by JonasKruckenberg** [comment]
That's strange it really seems like the plugin is not catching the import at all, what does your vite config look like?

**Comment by JonasKruckenberg** [comment]
So I've just created a few test cases with the vitejs create-app vue-ts and preact-ts templates importing images in a couple different way and I cannot reproduce your bug, I can only suspect that it's an issue with the solid plugin.
Can you confirm that this issue still exists when swapping the order of the plugins?
i.e. 
```ts
plugins: [
    solidPlugin(),
    imageTools()
  ],
```

instead of 
```ts
  plugins: [
    imageTools(),
    solidPlugin()
  ],
```

**Comment by YamiteruXYZ** [comment]
It still exists

**Comment by JonasKruckenberg** [comment]
Ohhhhh... I think I found it, can you try renaming your file from `.jpeg` to `.jpg`? I might have forgotten to alias jpeg to jpg 😅 
I'll push a fix for that asap though

**Comment by YamiteruXYZ** [comment]
Hell yeah now it's working!

**Comment by JonasKruckenberg** [comment]
It was a simple stupid typo in the include patterns lol 😅 
The fixed version should be pushed to rpm in a couple of minutes
