### ISSUE TITLE
Height doesn't change with width

### ISSUE THREAD

**Issue by YamiteruXYZ** [JonasKruckenberg/vite-imagetools#22]
I import image like this:
```typescript
import image from "./images/main.jpg?width=200;400&meta";
```

I get an array like this:
![image](https://user-images.githubusercontent.com/34185465/110815120-73831400-828a-11eb-9f5c-58beca4efa63.png)

As you can see the height property doesn't change with width.

**Comment by JonasKruckenberg** [comment]
Ohhh, alright this might be a bit more involved. The gist is:
The way imagetools collects the metadata is by first getting the input metadata and then merging it with the metadata generated by the directives.
This is because sharp does not give you access to the transformed metadata. 

So the image gets properly resized, but because you didn't specify a height it takes the original height. 

I'll have a look into it though and see if I can get it to work 👍🏻

**Comment by YamiteruXYZ** [comment]
You're very welcome 👍 

If we know the width and height of the original image can't we do something along the lines of:
```typescript
Math.round((newWidth/originalWidth)*originalHeight)
```

**Comment by JonasKruckenberg** [comment]
Yes that would've been my workaround, but turns out you can get the output-metadata by calling the toBuffer function if with a callback instead of using is as a promise. This should solve your problem 👍

It also has the nice side effect of removing all image metadata by default so your websites images don't leek privacy relevant data 🔥

**Comment by YamiteruXYZ** [comment]
Can you explain what you mean by "calling the toBuffer function if with a callback instead of using is as a promise". How do I do it? I don't understand. The current version (3.1.0) still has this bug.

**Comment by JonasKruckenberg** [comment]
The function call is an internal thing, it should just work. This is a bit weird but I’ll investigate it tomorrow:+1:

**Comment by JonasKruckenberg** [comment]
Alright so if you check you [the example](https://github.com/JonasKruckenberg/vite-imagetools/blob/8e44cb95493fdba7f92c2fa1811e95eb33956820/examples/simple/src/App.vue), I've set up a test for your issue using the latest version from npm.

On line 16 I import an image like so:
```js
  import image from "./assets/logo.png?width=200;400&meta";
```

and in the console I get the following output:
<img width="600" alt="screenshot" src="https://user-images.githubusercontent.com/25329995/111036181-48312e00-841e-11eb-8879-240fb51ee4b5.png">

You can see the height gets set to the correct number (the logo is square), so it should be working alright.

Maybe you can provide an example that reproduces your issue! 👍

**Comment by YamiteruXYZ** [comment]
Wtf now it works, but I haven't changed anything.. 🤔 Never mind.
